Add message body check (400) for http calls
eosnetworkfoundation/mandel pull request #200
Opened 2022-05-07 22:48 UTC by heifner

Apply parameters check for every http calls.
* If empty body is not allowed, then report `"A Request body is required"` with error code `400`.
* Require JSON body to contain data for JSON object, `{}` will report: `"A Request body is required"` with error code `400`.
* If unable to parse JSON object for http param report: `"Unable to parse valid input from POST body"` with error code `400`. 

- Resolves #198 
- Resolves #199

2022-05-09 19:40 UTC, ClaytonCalabrese requested changes

2022-05-09 19:40 UTC, ClaytonCalabrese commented on tests/plugin_http_api_test.py
> +        # get_required_keys with empty p4arameter
```suggestion
        # get_required_keys with empty parameter
```

2022-05-09 19:40 UTC, ClaytonCalabrese commented on unittests/plugin_tests.cpp
> +   {  // all spacee string
```suggestion
   {  // all space string
```

2022-05-09 19:40 UTC, ClaytonCalabrese commented on unittests/plugin_tests.cpp
> +   }
```suggestion
      const std::string str_no_space_both_side  = "a b";
      BOOST_REQUIRE(!str_no_space_both_side.empty());
      BOOST_CHECK_EQUAL(eosio::make_trimmed_string_view(str_no_space_both_side), str_no_space_both_side);

      const std::string str_with_leading_space = " " + str_no_space_both_side;
      BOOST_REQUIRE(!str_with_leading_space.empty());
      BOOST_CHECK_EQUAL(eosio::make_trimmed_string_view(str_with_leading_space), str_no_space_both_side);

      const std::string str_with_with_trailing_space = str_no_space_both_side + " ";
      BOOST_REQUIRE(!str_with_with_trailing_space.empty());
      BOOST_CHECK_EQUAL(eosio::make_trimmed_string_view(str_with_with_trailing_space), str_no_space_both_side);

      const std::string str_with_with_space_both_side = " " + str_no_space_both_side + " ";
      BOOST_REQUIRE(!str_with_with_space_both_side.empty());
      BOOST_CHECK_EQUAL(eosio::make_trimmed_string_view(str_with_with_space_both_side), str_no_space_both_side);
   }
```

2022-05-09 19:40 UTC, ClaytonCalabrese commented on unittests/plugin_tests.cpp
> +      BOOST_REQUIRE(! invalid_str_2.empty());
```suggestion
      BOOST_REQUIRE(!invalid_str_2.empty());
```

2022-05-09 21:30 UTC, heifner commented on plugins/producer_api_plugin/producer_api_plugin.cpp
> -     const auto& vs = fc::json::json::from_string(body).as<fc::variants>(); \
V = void, here it means it returns a void
R = param. So R_R means a method taking two params.

2022-05-09 21:48 UTC, heifner commented on plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
> +      no_params_required = 0,
renamed

2022-05-10 00:52 UTC, ClaytonCalabrese approved these changes

2022-05-11 01:05 UTC, merged