[3.2] Backport test contract fixes
eosnetworkfoundation/mandel pull request #622
Opened 2022-07-07 22:45 UTC by oschwaldp-oci

Resolving build issues with test-contracts

Building test contracts with prior versions of `mandel.cdt` requires the use of a version identifier:

`v1.7.x` requires use of `USE_EOSIO_CDT_1_7_X`
`v1.8.x` requires use of `USE_EOSIO_CDT_1_8_X`
`v3.0.0-rc1` and beyond does not require special parameters.

Build command argument example for building with `mandel.cdt` `v1.7.0`

`cmake -DUSE_EOSIO_CDT_1_7_X=true -DEOSIO_COMPILE_TEST_CONTRACTS=true -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`

Resolves: https://github.com/eosnetworkfoundation/mandel/issues/459

Backports: https://github.com/EOSIO/eos/pull/9114
Backports: https://github.com/EOSIO/eos/pull/9390

2022-07-08 00:54 UTC, heifner requested changes
Did you test with both eosio/cdt 1.7 and mandel/cdt?
Update the PR description with known supported cdt versions.

2022-07-08 00:54 UTC, heifner commented on unittests/CMakeLists.txt
> +   message( STATUS "Building contracts in directory `mandel/unittests/test-contracts/`" )
I think replace `mandel/` with `./`

2022-07-08 00:54 UTC, heifner commented on unittests/CMakeLists.txt
> +  message( STATUS "Not building contracts in directory `mandel/unittests/test-contracts/`" )
I think replace `mandel/` with `./`

2022-07-08 13:45 UTC, oschwaldp-oci commented on unittests/CMakeLists.txt
> +  message( STATUS "Not building contracts in directory `mandel/unittests/test-contracts/`" )
Good idea.  Addressed here: 77480b98bc4ad325ec59577ca5c3ca6a46a1b71b

2022-07-08 13:45 UTC, oschwaldp-oci commented on unittests/CMakeLists.txt
> +   message( STATUS "Building contracts in directory `mandel/unittests/test-contracts/`" )
Good idea.  Addressed here: 77480b98bc4ad325ec59577ca5c3ca6a46a1b71b

2022-07-09 02:27 UTC, heifner approved these changes

2022-07-09 03:40 UTC, merged