[3.1] make prune logs be at debug level except for the initial log when enabling purning
eosnetworkfoundation/mandel pull request #718
Opened 2022-07-24 21:06 UTC by spoonincode

Resolves #714. Log message when enabling pruning will now be at info level, continual logging messages that are rather spammy will be at debug level instead.

2022-07-25 13:50 UTC, heifner requested changes

2022-07-25 13:50 UTC, heifner commented on libraries/chain/block_log.cpp
> +                      "blocks.log pruned to blocks ${b}-${e}", fc::mutable_variant_object()("b", first_block_num)("e", head_num));
This is just creating a `log_message`, not actually logging.

2022-07-25 13:50 UTC, heifner commented on libraries/state_history/include/eosio/state_history/log.hpp
> +                      "${name}.log pruned to blocks ${b}-${e}", fc::mutable_variant_object()("name", name)("b", _begin_block)("e", _end_block - 1));
This is just creating a `log_message`, not actually logging.

2022-07-25 14:22 UTC, spoonincode commented
:facepalm: thanks, after I tested it I probably went back to refactor leaving a line out. I'm deal with it later

2022-07-28 18:55 UTC, spoonincode commented
This approach was a little long winded, but I liked it more than a
```
if(bool)
  ilog();
else
  dlog();
```
sort of thing. I couldn't find an existing interface that made it easy to `xlog(level, message, args)` :confused:

2022-07-28 21:37 UTC, heifner commented
> xlog(level, message, args)

You could add it.

2022-07-28 21:39 UTC, heifner requested changes

2022-07-28 21:39 UTC, heifner commented on libraries/chain/block_log.cpp
> +                                          "blocks.log pruned to blocks ${b}-${e}", fc::mutable_variant_object()("b", first_block_num)("e", head_num));
The log_msg is created even when not used, would be better to move it into the `if`.

2022-08-03 17:05 UTC, heifner approved these changes

2022-08-03 17:21 UTC, spoonincode commented
> You could add it.

Maybe worthwhile post-3.1

2022-08-03 17:21 UTC, merged