Backport cleos optional support
eosnetworkfoundation/mandel pull request #734
Opened 2022-07-29 13:24 UTC by ndcgundlach

Backport of changes to support nested optional<T>.

Resolves: https://github.com/eosnetworkfoundation/mandel/issues/721

2022-08-02 17:31 UTC, ClaytonCalabrese requested changes
Just a whitespace change

2022-08-03 00:22 UTC, spoonincode requested changes

2022-08-03 00:22 UTC, spoonincode commented on tests/nested_container_multi_index_test.py
> +exit(0)
I think this needs to check `testSuccessful` for the proper error code?

2022-08-03 16:50 UTC, ClaytonCalabrese approved these changes

2022-08-05 15:53 UTC, merged