WIP: Add new transaction retry integration test
eosnetworkfoundation/mandel pull request #89
Opened 2022-04-08 17:38 UTC by heifner

2022-04-14 20:35 UTC, brianjohnson5972 requested changes

2022-04-15 02:21 UTC, heifner commented on tests/Node.py
> +        if retry is not None:
Done.

2022-04-15 02:21 UTC, heifner commented on tests/Node.py
> +        assert isinstance(amountStr, str)
Done.

2022-04-15 04:34 UTC, brianjohnson5972 approved these changes

2022-04-15 04:34 UTC, merged