Configurable expired_accumulator_average_window
eosnetworkfoundation/mandel pull request #90
Opened 2022-04-08 23:51 UTC by ClaytonCalabrese

### Adds new config option subjective-account-decay-time-minutes to Producer Plugin

This value is used to calculate the expired_accumulator_average_window, thus making account decay time configurable. The passed value must be above 30, and defaults to 1440.

The default value for expired_accumulator_average_window remains the same.

2022-04-09 14:55 UTC, matthewdarwin commented
Can this be changed to >= 30 minutes?  (I am testing 30 in production right now)

2022-04-09 21:03 UTC, heifner requested changes

2022-04-09 21:03 UTC, heifner commented on plugins/producer_plugin/test/test_subjective_billing.cpp
> +      uint32_t window_size = sub_bill.get_expired_accumulator_average_window();
This is not used, so just remove it.

2022-04-11 11:32 UTC, heifner commented on plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
> +   uint32_t get_expired_accumulator_average_window() {
Make method `const`

2022-04-12 17:18 UTC, heifner commented on plugins/producer_plugin/producer_plugin.cpp
> +               "subjective-account-decay-time-minutes ${dt} must be greater than 0", ("dt", subjective_account_decay_time.to_seconds() * 60));
`/ 60` not `* 60`

2022-04-12 18:50 UTC, heifner approved these changes

2022-04-14 14:59 UTC, merged